server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## REST CLIENT -> http://localhost:4004/api/members
                    ## API GATEWAY -> http://member-service:4000/members
                    - id: member-service-route
                      uri: http://member-service:4000
                      predicates:
                        - Path=/api/members/**
                      filters:
                        - StripPrefix=1

                    ## REST CLIENT -> http://localhost:4004/api-docs/members
                    ## API GATEWAY -> http://member-service:4000/v3/api-docs
                    - id: api-docs-member-route
                      uri: http://member-service:4000
                      predicates:
                        - Path=/api-docs/members
                      filters:
                        - RewritePath=/api-docs/members,/v3/api-docs
